# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template actions.py.jinja --
from typing import TypeVar
import warnings

from . import types, errors, bases
from ._compat import model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED

if TYPE_CHECKING:
    from .client import Prisma
    from .bases import _PrismaModel


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class categoryActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: Prisma, model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.category]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await category.prisma().query_raw(
            'SELECT * FROM category WHERE id = ?',
            1103527590,
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.category
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await category.prisma().query_first(
            'SELECT * FROM category WHERE name = ?',
            'dhheabfhf',
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.categoryCreateInput,
        include: Optional[types.categoryInclude] = None
    ) -> _PrismaModelT:
        """Create a new category record.

        Parameters
        ----------
        data
            category record data
        include
            Specifies which relations should be loaded on the returned category model

        Returns
        -------
        prisma.models.category
            The created category record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a category record from just the required fields
        category = await category.prisma().create(
            data={
                # data to create a category record
                'name': 'ggciceaie',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def create_many(
        self,
        data: List[types.categoryCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple category records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of category record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await category.prisma().create_many(
            data=[
                {
                    # data to create a category record
                    'name': 'bbehjachib',
                },
                {
                    # data to create a category record
                    'name': 'cadfabfehe',
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if skip_duplicates and self._client._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._client._active_provider, 'create_many_skip_duplicates')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.categoryWhereUniqueInput,
        include: Optional[types.categoryInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single category record.

        Parameters
        ----------
        where
            category filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned category model

        Returns
        -------
        prisma.models.category
            The deleted category record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        category = await category.prisma().delete(
            where={
                'id': 368800899,
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def find_unique(
        self,
        where: types.categoryWhereUniqueInput,
        include: Optional[types.categoryInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique category record.

        Parameters
        ----------
        where
            category filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned category model

        Returns
        -------
        prisma.models.category
            The found category record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        category = await category.prisma().find_unique(
            where={
                'id': 1508029952,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return model_parse(self._model, result)

    async def find_unique_or_raise(
        self,
        where: types.categoryWhereUniqueInput,
        include: Optional[types.categoryInclude] = None
    ) -> _PrismaModelT:
        """Find a unique category record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            category filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned category model

        Returns
        -------
        prisma.models.category
            The found category record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        category = await category.prisma().find_unique_or_raise(
            where={
                'id': 486256185,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.categoryWhereInput] = None,
        cursor: Optional[types.categoryWhereUniqueInput] = None,
        include: Optional[types.categoryInclude] = None,
        order: Optional[Union[types.categoryOrderByInput, List[types.categoryOrderByInput]]] = None,
        distinct: Optional[List[types.categoryScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple category records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of category records returned
        skip
            Ignore the first N results
        where
            category filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned category model
        order
            Order the returned category records by any field
        distinct
            Filter category records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.category]
            The list of all category records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 category records
        categorys = await category.prisma().find_many(take=10)

        # find the first 5 category records ordered by the id field
        categorys = await category.prisma().find_many(
            take=5,
            order={
                'id': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [model_parse(self._model, r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.categoryWhereInput] = None,
        cursor: Optional[types.categoryWhereUniqueInput] = None,
        include: Optional[types.categoryInclude] = None,
        order: Optional[Union[types.categoryOrderByInput, List[types.categoryOrderByInput]]] = None,
        distinct: Optional[List[types.categoryScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single category record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            category filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned category model
        order
            Order the returned category records by any field
        distinct
            Filter category records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.category
            The first category record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second category record ordered by the name field
        category = await category.prisma().find_first(
            skip=1,
            order={
                'name': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None

        return model_parse(self._model, result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.categoryWhereInput] = None,
        cursor: Optional[types.categoryWhereUniqueInput] = None,
        include: Optional[types.categoryInclude] = None,
        order: Optional[Union[types.categoryOrderByInput, List[types.categoryOrderByInput]]] = None,
        distinct: Optional[List[types.categoryScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single category record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            category filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned category model
        order
            Order the returned category records by any field
        distinct
            Filter category records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.category
            The first category record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second category record ordered by the id field
        category = await category.prisma().find_first_or_raise(
            skip=1,
            order={
                'id': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update(
        self,
        data: types.categoryUpdateInput,
        where: types.categoryWhereUniqueInput,
        include: Optional[types.categoryInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single category record.

        Parameters
        ----------
        data
            category record data specifying what to update
        where
            category filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned category model

        Returns
        -------
        prisma.models.category
            The updated category record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        category = await category.prisma().update(
            where={
                'id': 1062517886,
            },
            data={
                # data to update the category record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def upsert(
        self,
        where: types.categoryWhereUniqueInput,
        data: types.categoryUpsertInput,
        include: Optional[types.categoryInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            category filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned category model

        Returns
        -------
        prisma.models.category
            The created or updated category record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        category = await category.prisma().upsert(
            where={
                'id': 267834847,
            },
            data={
                'create': {
                    'id': 267834847,
                    'name': 'cadfabfehe',
                },
                'update': {
                    'name': 'cadfabfehe',
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update_many(
        self,
        data: types.categoryUpdateManyMutationInput,
        where: types.categoryWhereInput,
    ) -> int:
        """Update multiple category records

        Parameters
        ----------
        data
            category data to update the selected category records to
        where
            Filter to select the category records to update

        Returns
        -------
        int
            The total number of category records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all category records
        total = await category.prisma().update_many(
            data={
                'name': 'biabhbdai'
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.categoryWhereInput] = None,
        cursor: Optional[types.categoryWhereUniqueInput] = None,
    ) -> int:
        """Count the number of category records present in the database

        Parameters
        ----------
        select
            Select the category fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            category filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.categoryCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await category.prisma().count()

        # results: prisma.types.categoryCountAggregateOutput
        results = await category.prisma().count(
            select={
                '_all': True,
                'id': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.categoryCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.categoryWhereInput] = None,
        cursor: Optional[types.categoryWhereUniqueInput] = None,
    ) -> types.categoryCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.categoryCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.categoryWhereInput] = None,
        cursor: Optional[types.categoryWhereUniqueInput] = None,
    ) -> Union[int, types.categoryCountAggregateOutput]:
        """Count the number of category records present in the database

        Parameters
        ----------
        select
            Select the category fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            category filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.categoryCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await category.prisma().count()

        # results: prisma.types.categoryCountAggregateOutput
        results = await category.prisma().count(
            select={
                '_all': True,
                'name': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.categoryCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.categoryWhereInput] = None
    ) -> int:
        """Delete multiple category records.

        Parameters
        ----------
        where
            Optional category filter to find the records to be deleted

        Returns
        -------
        int
            The total number of category records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all category records
        total = await category.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.categoryScalarFieldKeys'],
        *,
        where: Optional['types.categoryWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.categoryAvgAggregateInput'] = None,
        sum: Optional['types.categorySumAggregateInput'] = None,
        min: Optional['types.categoryMinAggregateInput'] = None,
        max: Optional['types.categoryMaxAggregateInput'] = None,
        having: Optional['types.categoryScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.categoryCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.categoryScalarFieldKeys', 'types.SortOrder'], List[Mapping['types.categoryScalarFieldKeys', 'types.SortOrder']]]] = None,
    ) -> List['types.categoryGroupByOutput']:
        """Group category records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar category fields to group records by
        where
            category filter to select records
        take
            Limit the maximum number of category records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.categoryGroupByOutput]
            A list of dictionaries representing the category record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group category records by id values
        # and count how many records are in each group
        results = await category.prisma().group_by(
            ['id'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]


class companyActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: Prisma, model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.company]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await company.prisma().query_raw(
            'SELECT * FROM company WHERE id = ?',
            836760821,
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.company
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await company.prisma().query_first(
            'SELECT * FROM company WHERE name = ?',
            'fjfddhigg',
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.companyCreateInput,
        include: Optional[types.companyInclude] = None
    ) -> _PrismaModelT:
        """Create a new company record.

        Parameters
        ----------
        data
            company record data
        include
            Specifies which relations should be loaded on the returned company model

        Returns
        -------
        prisma.models.company
            The created company record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a company record from just the required fields
        company = await company.prisma().create(
            data={
                # data to create a company record
                'name': 'hjaecfifb',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def create_many(
        self,
        data: List[types.companyCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple company records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of company record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await company.prisma().create_many(
            data=[
                {
                    # data to create a company record
                    'name': 'cbbbjbfcii',
                },
                {
                    # data to create a company record
                    'name': 'bbejhfidcb',
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if skip_duplicates and self._client._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._client._active_provider, 'create_many_skip_duplicates')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.companyWhereUniqueInput,
        include: Optional[types.companyInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single company record.

        Parameters
        ----------
        where
            company filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned company model

        Returns
        -------
        prisma.models.company
            The deleted company record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        company = await company.prisma().delete(
            where={
                'id': 1644289366,
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def find_unique(
        self,
        where: types.companyWhereUniqueInput,
        include: Optional[types.companyInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique company record.

        Parameters
        ----------
        where
            company filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned company model

        Returns
        -------
        prisma.models.company
            The found company record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        company = await company.prisma().find_unique(
            where={
                'id': 1388290519,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return model_parse(self._model, result)

    async def find_unique_or_raise(
        self,
        where: types.companyWhereUniqueInput,
        include: Optional[types.companyInclude] = None
    ) -> _PrismaModelT:
        """Find a unique company record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            company filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned company model

        Returns
        -------
        prisma.models.company
            The found company record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        company = await company.prisma().find_unique_or_raise(
            where={
                'id': 1647418052,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.companyWhereInput] = None,
        cursor: Optional[types.companyWhereUniqueInput] = None,
        include: Optional[types.companyInclude] = None,
        order: Optional[Union[types.companyOrderByInput, List[types.companyOrderByInput]]] = None,
        distinct: Optional[List[types.companyScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple company records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of company records returned
        skip
            Ignore the first N results
        where
            company filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned company model
        order
            Order the returned company records by any field
        distinct
            Filter company records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.company]
            The list of all company records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 company records
        companys = await company.prisma().find_many(take=10)

        # find the first 5 company records ordered by the description field
        companys = await company.prisma().find_many(
            take=5,
            order={
                'description': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [model_parse(self._model, r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.companyWhereInput] = None,
        cursor: Optional[types.companyWhereUniqueInput] = None,
        include: Optional[types.companyInclude] = None,
        order: Optional[Union[types.companyOrderByInput, List[types.companyOrderByInput]]] = None,
        distinct: Optional[List[types.companyScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single company record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            company filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned company model
        order
            Order the returned company records by any field
        distinct
            Filter company records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.company
            The first company record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second company record ordered by the id field
        company = await company.prisma().find_first(
            skip=1,
            order={
                'id': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None

        return model_parse(self._model, result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.companyWhereInput] = None,
        cursor: Optional[types.companyWhereUniqueInput] = None,
        include: Optional[types.companyInclude] = None,
        order: Optional[Union[types.companyOrderByInput, List[types.companyOrderByInput]]] = None,
        distinct: Optional[List[types.companyScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single company record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            company filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned company model
        order
            Order the returned company records by any field
        distinct
            Filter company records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.company
            The first company record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second company record ordered by the name field
        company = await company.prisma().find_first_or_raise(
            skip=1,
            order={
                'name': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update(
        self,
        data: types.companyUpdateInput,
        where: types.companyWhereUniqueInput,
        include: Optional[types.companyInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single company record.

        Parameters
        ----------
        data
            company record data specifying what to update
        where
            company filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned company model

        Returns
        -------
        prisma.models.company
            The updated company record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        company = await company.prisma().update(
            where={
                'id': 1675546029,
            },
            data={
                # data to update the company record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def upsert(
        self,
        where: types.companyWhereUniqueInput,
        data: types.companyUpsertInput,
        include: Optional[types.companyInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            company filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned company model

        Returns
        -------
        prisma.models.company
            The created or updated company record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        company = await company.prisma().upsert(
            where={
                'id': 1767274722,
            },
            data={
                'create': {
                    'id': 1767274722,
                    'name': 'bbejhfidcb',
                },
                'update': {
                    'name': 'bbejhfidcb',
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update_many(
        self,
        data: types.companyUpdateManyMutationInput,
        where: types.companyWhereInput,
    ) -> int:
        """Update multiple company records

        Parameters
        ----------
        data
            company data to update the selected company records to
        where
            Filter to select the company records to update

        Returns
        -------
        int
            The total number of company records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all company records
        total = await company.prisma().update_many(
            data={
                'description': 'dcgchcbbf'
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.companyWhereInput] = None,
        cursor: Optional[types.companyWhereUniqueInput] = None,
    ) -> int:
        """Count the number of company records present in the database

        Parameters
        ----------
        select
            Select the company fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            company filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.companyCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await company.prisma().count()

        # results: prisma.types.companyCountAggregateOutput
        results = await company.prisma().count(
            select={
                '_all': True,
                'id': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.companyCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.companyWhereInput] = None,
        cursor: Optional[types.companyWhereUniqueInput] = None,
    ) -> types.companyCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.companyCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.companyWhereInput] = None,
        cursor: Optional[types.companyWhereUniqueInput] = None,
    ) -> Union[int, types.companyCountAggregateOutput]:
        """Count the number of company records present in the database

        Parameters
        ----------
        select
            Select the company fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            company filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.companyCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await company.prisma().count()

        # results: prisma.types.companyCountAggregateOutput
        results = await company.prisma().count(
            select={
                '_all': True,
                'name': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.companyCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.companyWhereInput] = None
    ) -> int:
        """Delete multiple company records.

        Parameters
        ----------
        where
            Optional company filter to find the records to be deleted

        Returns
        -------
        int
            The total number of company records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all company records
        total = await company.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.companyScalarFieldKeys'],
        *,
        where: Optional['types.companyWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.companyAvgAggregateInput'] = None,
        sum: Optional['types.companySumAggregateInput'] = None,
        min: Optional['types.companyMinAggregateInput'] = None,
        max: Optional['types.companyMaxAggregateInput'] = None,
        having: Optional['types.companyScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.companyCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.companyScalarFieldKeys', 'types.SortOrder'], List[Mapping['types.companyScalarFieldKeys', 'types.SortOrder']]]] = None,
    ) -> List['types.companyGroupByOutput']:
        """Group company records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar company fields to group records by
        where
            company filter to select records
        take
            Limit the maximum number of company records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.companyGroupByOutput]
            A list of dictionaries representing the company record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group company records by description values
        # and count how many records are in each group
        results = await company.prisma().group_by(
            ['description'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]


class productActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: Prisma, model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.product]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await product.prisma().query_raw(
            'SELECT * FROM product WHERE id = ?',
            1343201072,
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.product
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await product.prisma().query_first(
            'SELECT * FROM product WHERE name = ?',
            'ghfhiafcb',
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.productCreateInput,
        include: Optional[types.productInclude] = None
    ) -> _PrismaModelT:
        """Create a new product record.

        Parameters
        ----------
        data
            product record data
        include
            Specifies which relations should be loaded on the returned product model

        Returns
        -------
        prisma.models.product
            The created product record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a product record from just the required fields
        product = await product.prisma().create(
            data={
                # data to create a product record
                'name': 'heejgedji',
                'price': 1969681615.111617,
                'companyId': 861472101,
                'categoryId': 1303003706,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def create_many(
        self,
        data: List[types.productCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple product records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of product record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await product.prisma().create_many(
            data=[
                {
                    # data to create a product record
                    'name': 'bgiggdidbf',
                    'price': 2000430152.186814,
                    'companyId': 1860847622,
                    'categoryId': 1448521415,
                },
                {
                    # data to create a product record
                    'name': 'bgcigfahea',
                    'price': 1249606685.83590,
                    'companyId': 763719779,
                    'categoryId': 429995104,
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if skip_duplicates and self._client._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._client._active_provider, 'create_many_skip_duplicates')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.productWhereUniqueInput,
        include: Optional[types.productInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single product record.

        Parameters
        ----------
        where
            product filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned product model

        Returns
        -------
        prisma.models.product
            The deleted product record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        product = await product.prisma().delete(
            where={
                'id': 1775811865,
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def find_unique(
        self,
        where: types.productWhereUniqueInput,
        include: Optional[types.productInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique product record.

        Parameters
        ----------
        where
            product filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned product model

        Returns
        -------
        prisma.models.product
            The found product record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        product = await product.prisma().find_unique(
            where={
                'id': 893145566,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return model_parse(self._model, result)

    async def find_unique_or_raise(
        self,
        where: types.productWhereUniqueInput,
        include: Optional[types.productInclude] = None
    ) -> _PrismaModelT:
        """Find a unique product record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            product filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned product model

        Returns
        -------
        prisma.models.product
            The found product record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        product = await product.prisma().find_unique_or_raise(
            where={
                'id': 995405759,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.productWhereInput] = None,
        cursor: Optional[types.productWhereUniqueInput] = None,
        include: Optional[types.productInclude] = None,
        order: Optional[Union[types.productOrderByInput, List[types.productOrderByInput]]] = None,
        distinct: Optional[List[types.productScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple product records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of product records returned
        skip
            Ignore the first N results
        where
            product filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned product model
        order
            Order the returned product records by any field
        distinct
            Filter product records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.product]
            The list of all product records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 product records
        products = await product.prisma().find_many(take=10)

        # find the first 5 product records ordered by the description field
        products = await product.prisma().find_many(
            take=5,
            order={
                'description': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [model_parse(self._model, r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.productWhereInput] = None,
        cursor: Optional[types.productWhereUniqueInput] = None,
        include: Optional[types.productInclude] = None,
        order: Optional[Union[types.productOrderByInput, List[types.productOrderByInput]]] = None,
        distinct: Optional[List[types.productScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single product record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            product filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned product model
        order
            Order the returned product records by any field
        distinct
            Filter product records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.product
            The first product record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second product record ordered by the price field
        product = await product.prisma().find_first(
            skip=1,
            order={
                'price': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None

        return model_parse(self._model, result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.productWhereInput] = None,
        cursor: Optional[types.productWhereUniqueInput] = None,
        include: Optional[types.productInclude] = None,
        order: Optional[Union[types.productOrderByInput, List[types.productOrderByInput]]] = None,
        distinct: Optional[List[types.productScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single product record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            product filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned product model
        order
            Order the returned product records by any field
        distinct
            Filter product records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.product
            The first product record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second product record ordered by the companyId field
        product = await product.prisma().find_first_or_raise(
            skip=1,
            order={
                'companyId': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update(
        self,
        data: types.productUpdateInput,
        where: types.productWhereUniqueInput,
        include: Optional[types.productInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single product record.

        Parameters
        ----------
        data
            product record data specifying what to update
        where
            product filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned product model

        Returns
        -------
        prisma.models.product
            The updated product record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        product = await product.prisma().update(
            where={
                'id': 2102736524,
            },
            data={
                # data to update the product record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def upsert(
        self,
        where: types.productWhereUniqueInput,
        data: types.productUpsertInput,
        include: Optional[types.productInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            product filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned product model

        Returns
        -------
        prisma.models.product
            The created or updated product record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        product = await product.prisma().upsert(
            where={
                'id': 271520213,
            },
            data={
                'create': {
                    'id': 271520213,
                    'name': 'bgcigfahea',
                    'price': 1249606685.83590,
                    'companyId': 763719779,
                    'categoryId': 429995104,
                },
                'update': {
                    'name': 'bgcigfahea',
                    'price': 1249606685.83590,
                    'companyId': 763719779,
                    'categoryId': 429995104,
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update_many(
        self,
        data: types.productUpdateManyMutationInput,
        where: types.productWhereInput,
    ) -> int:
        """Update multiple product records

        Parameters
        ----------
        data
            product data to update the selected product records to
        where
            Filter to select the product records to update

        Returns
        -------
        int
            The total number of product records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all product records
        total = await product.prisma().update_many(
            data={
                'categoryId': 456633834
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.productWhereInput] = None,
        cursor: Optional[types.productWhereUniqueInput] = None,
    ) -> int:
        """Count the number of product records present in the database

        Parameters
        ----------
        select
            Select the product fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            product filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.productCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await product.prisma().count()

        # results: prisma.types.productCountAggregateOutput
        results = await product.prisma().count(
            select={
                '_all': True,
                'id': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.productCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.productWhereInput] = None,
        cursor: Optional[types.productWhereUniqueInput] = None,
    ) -> types.productCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.productCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.productWhereInput] = None,
        cursor: Optional[types.productWhereUniqueInput] = None,
    ) -> Union[int, types.productCountAggregateOutput]:
        """Count the number of product records present in the database

        Parameters
        ----------
        select
            Select the product fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            product filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.productCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await product.prisma().count()

        # results: prisma.types.productCountAggregateOutput
        results = await product.prisma().count(
            select={
                '_all': True,
                'name': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.productCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.productWhereInput] = None
    ) -> int:
        """Delete multiple product records.

        Parameters
        ----------
        where
            Optional product filter to find the records to be deleted

        Returns
        -------
        int
            The total number of product records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all product records
        total = await product.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.productScalarFieldKeys'],
        *,
        where: Optional['types.productWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.productAvgAggregateInput'] = None,
        sum: Optional['types.productSumAggregateInput'] = None,
        min: Optional['types.productMinAggregateInput'] = None,
        max: Optional['types.productMaxAggregateInput'] = None,
        having: Optional['types.productScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.productCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.productScalarFieldKeys', 'types.SortOrder'], List[Mapping['types.productScalarFieldKeys', 'types.SortOrder']]]] = None,
    ) -> List['types.productGroupByOutput']:
        """Group product records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar product fields to group records by
        where
            product filter to select records
        take
            Limit the maximum number of product records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.productGroupByOutput]
            A list of dictionaries representing the product record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group product records by description values
        # and count how many records are in each group
        results = await product.prisma().group_by(
            ['description'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]



def _select_fields(root: str, select: Mapping[str, Any]) -> str:
    """Helper to build a GraphQL selection string

    This is a work around until field selection is added to the query builder.
    """

    return root + ' {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))


from . import models