from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'category',
    'company',
    'product',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'category': {
        'product': 'product',
    },
    'company': {
        'product': 'product',
    },
    'product': {
        'category': 'category',
        'company': 'company',
    },
}

# fmt: on